# Generated by Django 3.0.3 on 2020-02-18 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(help_text='01/01/2020 09:00')),
                ('ubicacion_obra', models.CharField(max_length=100)),
                ('dias', models.IntegerField()),
                ('presentacion', models.NullBooleanField()),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('fecha_presenta', models.DateField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
        ),
    ]
