# Generated by Django 3.0.3 on 2020-02-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='presentacion',
            field=models.NullBooleanField(default=False),
        ),
    ]
