# Generated by Django 3.0.3 on 2020-02-11 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectista', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('dir_obra', models.CharField(max_length=50)),
                ('precio_metro', models.IntegerField()),
                ('metros', models.IntegerField()),
                ('total', models.IntegerField(editable=False)),
                ('cuota', models.BooleanField(default=False)),
                ('pago', models.IntegerField(default=0)),
                ('pago2', models.IntegerField(default=0)),
                ('fecha_pago2', models.DateField(blank=True, null=True)),
                ('pago3', models.IntegerField(default=0)),
                ('fecha_pago3', models.DateField(blank=True, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('deuda', models.PositiveIntegerField(editable=False)),
                ('valor_cuota', models.PositiveIntegerField(editable=False)),
                ('s_cuota1', models.PositiveIntegerField(editable=False)),
                ('s_cuota2', models.PositiveIntegerField(editable=False)),
                ('s_cuota3', models.PositiveIntegerField(editable=False)),
                ('proyectista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectista.Proyectista')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
        ),
    ]
