# Generated by Django 3.0.3 on 2020-02-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='valor_cuota',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
