# Generated by Django 3.0.3 on 2020-02-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plano', '0002_plano_valor_cuota'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='s_cuota1',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plano',
            name='s_cuota2',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plano',
            name='s_cuota3',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
