# Generated by Django 3.0.3 on 2020-03-10 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cementerio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cementerio',
            name='dias_trabajo',
        ),
        migrations.RemoveField(
            model_name='cementerio',
            name='final_trabajo',
        ),
    ]
