# Generated by Django 3.0.3 on 2020-03-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cementerio', '0002_auto_20200310_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cementerio',
            name='fecha_compra',
            field=models.DateTimeField(),
        ),
    ]
