# Generated by Django 3.0.3 on 2020-02-16 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(help_text='01/01/2020 09:00')),
                ('lugar', models.CharField(max_length=60)),
                ('caracteristicas', models.CharField(max_length=60)),
                ('hechos', models.CharField(max_length=200)),
                ('situacion', models.NullBooleanField(default=False)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
        ),
    ]
